### ISSUE TITLE
Unable to redeploy when once bound

### ISSUE THREAD

**Issue by algas** [stuartpb/dokku-bind-port#5]
I was using this plugin on dokku-alt server. After I bound a port with an docker app container, I was not able to rebuild or redeploy without unbounding the port.
```
$ sudo dokku bind:create app-name 12345 12345
$ sudo dokku rebuild app-name
...
Error response from daemon: Cannot start container (container_id): Bind for 0.0.0.0:12345 failed: port is already allocated
```
What am I supposed to do?

**Comment by stuartpb** [comment]
Closed by [deprecation](https://github.com/stuartpb/dokku-bind-port/commit/126f61dd551278dcd4b7698e21328fedf39ffad4). If you want a platform that can bind app ports, use Plushu.
