### ISSUE TITLE
is it possible bind the adress too?

### ISSUE THREAD

**Issue by Kikobeats** [stuartpb/dokku-bind-port#6]
I detect that my running containers under dokku haven't the IP address of the machined binded. Is is possible to solve with this plugin?

**Comment by stuartpb** [comment]
This plugin wouldn't handle it, but you might be able to do something like that with a custom Docker configuration and the dokku-docker-options plugin. [See the Docker documentation.](https://docs.docker.com/articles/networking/#binding-ports)
