### ISSUE TITLE
Thanks for the deprecation note

### ISSUE THREAD

**Issue by haifengkao** [stuartpb/dokku-bind-port#7]
I have been trying to make this plugin work for the whole day. 
Your deprecation note really saves my day. Now I can try something else :p

**Comment by stuartpb** [comment]
It was actually you starring the repo that triggered it - I was like "wait a sec, hey now, nobody should be starring that project any more".

**Comment by haifengkao** [comment]
Haha, your project is the first page on Google. I believe someone will find this deprecation note useful from time to time. 
Thank you stuartpb.
