### ISSUE TITLE
errors on Dokku 4

### ISSUE THREAD

**Issue by busla** [stuartpb/dokku-bind-port#8]
I get this errors on Dokku 4:
`/var/lib/dokku/plugins/available/dokku-bind-port/plugin.toml: no such file or directory`
I installed the plugin using `$ dokku plugin:install https://github.com/stuartpb/dokku-bind-port`

It does seem to work though.

**Comment by stuartpb** [comment]
I stopped maintaining this years before Dokku switched to its goofy overengineered plugin.toml thing, in favor of [Plushu](https://github.com/plushu/plushu) and its [plushu-app-docker-opts](https://github.com/plushu/plushu-app-docker-opts) plugin. See the first section of [the README](https://github.com/stuartpb/dokku-bind-port/blob/master/README.md).
